# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0UGfcmvtEhQZaj15uUCLUs0CvHFdHD8
"""

import json
import boto3
from datetime import datetime

s3 = boto3.client("s3")
BUCKET = "weather-data-els9cy"

# 5 major airports
AIRPORTS = {
    "CA": {"lat": 35.35474, "lon": -116.885329},
    "AS": {"lat": 34.9428028, "lon": -97.8180194},
    "AZ": {"lat": 34.3055992, "lon": -112.165001},
    "AA": {"lat": 38.704022, "lon": -101.473911},
    "WN": {"lat": 46.25, "lon": -117.249001}
}

def lambda_handler(event, context):
    start_year = 1999
    end_year = 2025

    for airport, coords in AIRPORTS.items():
        data_list = []

        for year in range(start_year, end_year + 1):
            for month in range(1, 13):
                # Generate sample weather data
                data_list.append({
                    "year": year,
                    "month": month,
                    "coord": coords,
                    "main": {
                        "temp": round(15 + 10*(month/12), 2),
                        "humidity": 50 + month % 50
                    },
                    "weather": [
                        {
                            "main": "Clear" if month < 10 else "Rain",
                            "description": "clear sky" if month < 10 else "rainy"
                        }
                    ],
                    "wind": {
                        "speed": round(3 + 2*(month%5), 2),
                        "deg": (month*30) % 360
                    },
                    "dt": int(datetime(year, month, 1).timestamp())
                })

        # Upload one JSON per airport
        s3_key = f"weather/{airport}.json"
        s3.put_object(Bucket=BUCKET, Key=s3_key, Body=json.dumps(data_list))
        print(f"Saved {airport} weather data ({len(data_list)} records) to {s3_key}")

    return {
        "statusCode": 200,
        "body": "Sample weather data generated for all airports (1999–2025)"
    }